const books = [
  {
    author: "Chinua Achebe",
    country: "Nigeria",
    imageLink: "assets/images/things-fall-apart.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    pages: 209,
    title: "Things Fall Apart",
    year: 1958,
    category: "Fiction",
    ISBN: "1234",
    price: 15.99,
  },
  {
    author: "Hans Christian Andersen",
    country: "Denmark",
    imageLink: "assets/images/fairy-tales.jpg",
    language: "Danish",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 784,
    title: "Fairy tales",
    year: 1836,
    category: "Children's Literature",
    ISBN: "5678",
    price: 12.5,
  },
  {
    author: "Dante Alighieri",
    country: "Italy",
    imageLink: "assets/images/the-divine-comedy.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    pages: 928,
    title: "The Divine Comedy",
    year: 1315,
    category: "Classic",
    ISBN: "9012",
    price: 9.99,
  },
  {
    author: "Unknown",
    country: "Sumer and Akkadian Empire",
    imageLink: "assets/images/the-epic-of-gilgamesh.jpg",
    language: "Akkadian",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    pages: 160,
    title: "The Epic Of Gilgamesh",
    year: 1700,
    category: "Classic",
    ISBN: "3456",
    price: 8.99,
  },
  {
    author: "Unknown",
    country: "Achaemenid Empire",
    imageLink: "assets/images/the-book-of-job.jpg",
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "The Book Of Job",
    year: 600,
    category: "Classic",
    ISBN: "7890",
    price: 17.99,
  },
  {
    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: "assets/images/one-thousand-and-one-nights.jpg",
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "One Thousand and One Nights",
    year: 1200,
    category: "Children's Literature",
    ISBN: "5678",
    price: 12.5,
  },
  {
    author: "Unknown",
    country: "Iceland",
    imageLink: "assets/images/njals-saga.jpg",
    language: "Old Norse",
    link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    pages: 384,
    title: "Nj\u00e1l's Saga",
    year: 1350,
    category: "Children's Literature",
    ISBN: "5678",
    price: 12.5,
  },
  {
    author: "Jane Austen",
    country: "United Kingdom",
    imageLink: "assets/images/pride-and-prejudice.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    pages: 226,
    title: "Pride and Prejudice",
    year: 1813,
    category: "Classic",
    ISBN: "3456",
    price: 8.99,
  },
  {
    author: "Honor\u00e9 de Balzac",
    country: "France",
    imageLink: "assets/images/le-pere-goriot.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    pages: 443,
    title: "Le P\u00e8re Goriot",
    year: 1835,
    category: "Classic",
    ISBN: "7890",
    price: 17.99,
  },
  {
    author: "Samuel Beckett",
    country: "Republic of Ireland",
    imageLink: "assets/images/molloy-malone-dies-the-unnamable.jpg",
    language: "French, English",
    link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    pages: 256,
    title: "Molloy, Malone Dies, The Unnamable, the trilogy",
    year: 1952,
    category: "Children's Literature",
    ISBN: "5678",
    price: 12.5,
  },
  {
    author: "Giovanni Boccaccio",
    country: "Italy",
    imageLink: "assets/images/the-decameron.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/The_Decameron\n",
    pages: 1024,
    title: "The Decameron",
    year: 1351,
    category: "Classic",
    ISBN: "3456",
    price: 8.99,
  },
  {
    author: "Jorge Luis Borges",
    country: "Argentina",
    imageLink: "assets/images/ficciones.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    pages: 224,
    title: "Ficciones",
    year: 1965,
    category: "Fiction",
    ISBN: "1234",
    price: 15.99,
  },
  {
    author: "Emily Bront\u00eb",
    country: "United Kingdom",
    imageLink: "assets/images/wuthering-heights.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    pages: 342,
    title: "Wuthering Heights",
    year: 1847,
    category: "Classic",
    ISBN: "3456",
    price: 8.99,
  },
  {
    author: "Jorge Luis Borges",
    country: "Argentina",
    imageLink: "assets/images/ficciones.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    pages: 224,
    title: "Ficciones",
    year: 1965,
    category: "Fiction",
    ISBN: "1234",
    price: 15.99,
  },
  {
    author: "Emily Bront\u00eb",
    country: "United Kingdom",
    imageLink: "assets/images/wuthering-heights.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    pages: 342,
    title: "Wuthering Heights",
    year: 1847,
    category: "Classic",
    ISBN: "9012",
    price: 9.99,
  },
  {
    author: "Albert Camus",
    country: "Algeria, French Empire",
    imageLink: "assets/images/l-etranger.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    pages: 185,
    title: "The Stranger",
    year: 1942,
    category: "Children's Literature",
    ISBN: "5678",
    price: 12.5,
  },
];
export default books;
